using Microsoft.VisualStudio.TestTools.UnitTesting;
using QuantityMeasurementApp.BusinessLayer.Services;
using QuantityMeasurementApp.ModelLayer.DTO;
using QuantityMeasurementApp.ModelLayer.Entities;
using QuantityMeasurementApp.ModelLayer.Models;
using QuantityMeasurementApp.RepoLayer.Repositories;

namespace QuantityMeasurementApp.Tests
{
    /// <summary>UC15 - N-Tier Architecture Tests using InMemoryQuantityRepository.</summary>
    [TestClass]
    [DoNotParallelize]
    public class UC15_NTierArchitectureTest
    {
        private InMemoryQuantityRepository     _repository;
        private QuantityMeasurementServiceImpl _service;

        [TestInitialize]
        public void SetUp()
        {
            _repository = new InMemoryQuantityRepository();
            _service    = new QuantityMeasurementServiceImpl(_repository);
        }

        // ── Entity Tests ──────────────────────────────────────────────────

        [TestMethod]
        public void Entity_Constructor_ShouldStoreAllFieldsCorrectly()
        {
            var e = new QuantityMeasurementEntity("COMPARE","1 FEET","12 INCHES","True","LENGTH");
            Assert.AreEqual("COMPARE",   e.Operation);
            Assert.AreEqual("1 FEET",    e.OperandOne);
            Assert.AreEqual("12 INCHES", e.OperandTwo);
            Assert.AreEqual("True",      e.Result);
        }

        [TestMethod]
        public void Entity_Id_ShouldBeAutoGenerated()
        {
            var e = new QuantityMeasurementEntity("COMPARE","1 FEET","12 INCHES","True","LENGTH");
            Assert.AreNotEqual(System.Guid.Empty, e.Id);
        }

        [TestMethod]
        public void Entity_TwoInstances_ShouldHaveDifferentIds()
        {
            var e1 = new QuantityMeasurementEntity("COMPARE","1 FEET","12 INCHES","True","LENGTH");
            var e2 = new QuantityMeasurementEntity("COMPARE","1 FEET","12 INCHES","True","LENGTH");
            Assert.AreNotEqual(e1.Id, e2.Id);
        }

        // ── Repository Tests ──────────────────────────────────────────────

        [TestMethod]
        public void Repository_Save_ShouldAddEntityToList()
        {
            _repository.Save(new QuantityMeasurementEntity("COMPARE","1 FEET","12 INCHES","True","LENGTH"));
            Assert.AreEqual(1, _repository.GetTotalCount());
        }

        [TestMethod]
        public void Repository_GetAll_ShouldReturnNonNullList()
            => Assert.IsNotNull(_repository.GetAll());

        // ── Service Tests - Compare ───────────────────────────────────────

        [TestMethod]
        public void Service_Compare_OneFeetAndTwelveInches_ShouldReturnTrue()
        {
            var dto = _service.Compare(
                new QuantityDTO(1, LengthEnum.FEET), new QuantityDTO(12, LengthEnum.INCHES));
            Assert.AreEqual("true", dto.Result);
        }

        [TestMethod]
        public void Service_Compare_DifferentValues_ShouldReturnFalse()
        {
            var dto = _service.Compare(
                new QuantityDTO(1, LengthEnum.FEET), new QuantityDTO(2, LengthEnum.FEET));
            Assert.AreEqual("false", dto.Result);
        }

        [TestMethod]
        public void Service_Compare_OneKgAndThousandGrams_ShouldReturnTrue()
        {
            var dto = _service.Compare(
                new QuantityDTO(1, WeightEnum.KILOGRAM), new QuantityDTO(1000, WeightEnum.GRAM));
            Assert.AreEqual("true", dto.Result);
        }

        [TestMethod]
        public void Service_Compare_OneLitreAndThousandMl_ShouldReturnTrue()
        {
            var dto = _service.Compare(
                new QuantityDTO(1, VolumeEnum.LITRE), new QuantityDTO(1000, VolumeEnum.MILLILITRE));
            Assert.AreEqual("true", dto.Result);
        }

        [TestMethod]
        public void Service_Compare_ShouldSaveToRepository()
        {
            _service.Compare(new QuantityDTO(1, LengthEnum.FEET), new QuantityDTO(12, LengthEnum.INCHES));
            Assert.AreEqual(1, _repository.GetTotalCount());
        }

        // ── Service Tests - Convert ───────────────────────────────────────

        [TestMethod]
        public void Service_Convert_OneFeetToInches_ShouldReturnTwelve()
        {
            var dto = _service.Convert(new QuantityDTO(1, LengthEnum.FEET), LengthEnum.INCHES);
            Assert.IsTrue(dto.Result.Contains("12"));
        }

        [TestMethod]
        public void Service_Convert_OneKilogramToGram_ShouldReturnThousand()
        {
            var dto = _service.Convert(new QuantityDTO(1, WeightEnum.KILOGRAM), WeightEnum.GRAM);
            Assert.IsTrue(dto.Result.Contains("1000"));
        }

        // ── Service Tests - Add ───────────────────────────────────────────

        [TestMethod]
        public void Service_Add_OneFeetAndTwelveInches_ShouldReturnTwoFeet()
        {
            var dto = _service.Add(
                new QuantityDTO(1, LengthEnum.FEET), new QuantityDTO(12, LengthEnum.INCHES), LengthEnum.FEET);
            Assert.IsTrue(dto.Result.Contains("2"));
        }

        [TestMethod]
        public void Service_Add_OneKgAndThousandGrams_ShouldReturnTwoKg()
        {
            var dto = _service.Add(
                new QuantityDTO(1, WeightEnum.KILOGRAM), new QuantityDTO(1000, WeightEnum.GRAM), WeightEnum.KILOGRAM);
            Assert.IsTrue(dto.Result.Contains("2"));
        }

        // ── Service Tests - Subtract ──────────────────────────────────────

        [TestMethod]
        public void Service_Subtract_TwoFeetMinusOneFeet_ShouldReturnOneFeet()
        {
            var dto = _service.Subtract(
                new QuantityDTO(2, LengthEnum.FEET), new QuantityDTO(1, LengthEnum.FEET));
            Assert.IsTrue(dto.Result.Contains("1"));
        }

        // ── Service Tests - Divide ────────────────────────────────────────

        [TestMethod]
        public void Service_Divide_TwoFeetByOneFeet_ShouldReturnTwo()
        {
            var dto = _service.Divide(
                new QuantityDTO(2, LengthEnum.FEET), new QuantityDTO(1, LengthEnum.FEET));
            Assert.IsTrue(dto.Result.Contains("2"));
        }

        // ── Backward Compatibility UC1-UC14 ──────────────────────────────

        [TestMethod]
        public void BackwardCompatibility_UC1_FeetEquality()
        {
            var dto = _service.Compare(
                new QuantityDTO(1, LengthEnum.FEET), new QuantityDTO(1, LengthEnum.FEET));
            Assert.AreEqual("true", dto.Result);
        }

        [TestMethod]
        public void BackwardCompatibility_UC3_FeetToInches()
        {
            var dto = _service.Compare(
                new QuantityDTO(1, LengthEnum.FEET), new QuantityDTO(12, LengthEnum.INCHES));
            Assert.AreEqual("true", dto.Result);
        }

        [TestMethod]
        public void BackwardCompatibility_UC9_WeightEquality()
        {
            var dto = _service.Compare(
                new QuantityDTO(1, WeightEnum.KILOGRAM), new QuantityDTO(1000, WeightEnum.GRAM));
            Assert.AreEqual("true", dto.Result);
        }

        [TestMethod]
        public void BackwardCompatibility_UC11_VolumeEquality()
        {
            var dto = _service.Compare(
                new QuantityDTO(1, VolumeEnum.LITRE), new QuantityDTO(1000, VolumeEnum.MILLILITRE));
            Assert.AreEqual("true", dto.Result);
        }

        [TestMethod]
        public void BackwardCompatibility_UC14_TemperatureComparison()
        {
            var t1 = new Quantity<TemperatureEnum>(0,  TemperatureEnum.CELSIUS);
            var t2 = new Quantity<TemperatureEnum>(32, TemperatureEnum.FAHRENHEIT);
            Assert.IsTrue(t1.Equals(t2));
        }

        [TestMethod]
        public void BackwardCompatibility_UC14_TemperatureAddition_ShouldThrow()
        {
            var t1 = new Quantity<TemperatureEnum>(100, TemperatureEnum.CELSIUS);
            var t2 = new Quantity<TemperatureEnum>(50,  TemperatureEnum.CELSIUS);
            try { t1.Add(t2, TemperatureEnum.CELSIUS); Assert.Fail("Expected exception."); }
            catch (System.NotSupportedException) { Assert.IsTrue(true); }
        }

        [TestMethod]
        public void Service_MultipleOperations_ShouldAllBeSaved()
        {
            _service.Compare(new QuantityDTO(1, LengthEnum.FEET),    new QuantityDTO(12,   LengthEnum.INCHES));
            _service.Add(    new QuantityDTO(1, WeightEnum.KILOGRAM), new QuantityDTO(1000, WeightEnum.GRAM), WeightEnum.KILOGRAM);
            _service.Convert(new QuantityDTO(1, VolumeEnum.LITRE),    VolumeEnum.MILLILITRE);
            Assert.AreEqual(3, _repository.GetTotalCount());
        }
    }
}
